[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# 优化函数配置
[[functions]]
  function = "stylize-image-background"
  timeout = 300  # 5分钟超时
  memory = 1024  # 1GB 内存

[[functions]]
  function = "stylize-image-status"
  timeout = 10   # 10秒超时
  memory = 512   # 512MB 内存 